name: Deploy to Railway

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.14.1-focal

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "LOGIN_URL=${{ secrets.LOGIN_URL }}" >> .env
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> .env
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          cat .env

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | bash
          echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $GITHUB_ENV
          
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_TOKEN: "1dac405b-26b4-431c-bbcb-a9b598bc0e89"
        run: |
          . $GITHUB_ENV
          railway up --service atec --environment production
